name: "Generate go protos"
on:
  push:
    branches:
      - feature/*
env:
  GO_VERSION: 1.23
jobs:
  generate:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: cnc-csku/task-nexus-proto-go
          ref: main
          path: task-nexus-proto-go
          token: ${{ secrets.GH_PAT }}

      - name: Set buf cli
        uses: bufbuild/buf-setup-action@v1

      - name: Build protos
        run: |
          cd task-nexus-proto-go
          buf generate

      - name: Commit generated code
        run: |
          cd task-nexus-proto-go
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add --all
          git commit -m "Update generated code"
          git push https://github.com/cnc-csku/task-nexus-proto-go.git HEAD:main
