name: "Generate go protos"
on:
  push:
    branches:
      - main
env:
  GO_VERSION: 1.23
jobs:
  generate:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout proto-go repo
        uses: actions/checkout@v4
        with:
          repository: cnc-csku/task-nexus-proto-go
          ref: main
          path: task-nexus-proto-go
          token: ${{ secrets.GH_PAT }}

      - name: Set buf cli
        uses: bufbuild/buf-setup-action@v1

      - name: Build protos
        run: |
          cd task-nexus-proto-go
          buf generate 

      - name: Create version tag
        id: create_tag
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          MAJOR=${{ vars.MAIN_MAJOR_VERSION }}
          MINOR=$((${{ vars.MAIN_MINOR_VERSION }} + 1))
          PATCH=0

          gh variable set MAIN_MINOR_VERSION --body $MINOR

          echo v$MAJOR.$MINOR.$PATCH
          echo "TARGET_VERSION=$TARGET_VERSION" >> $GITHUB_OUTPUT

      - name: Commit generated code
        run: |
          cd task-nexus-proto-go
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add --all
          git commit -m "Update generated code"
          git tag -v ${{ steps.create_tag.outputs.TARGET_VERSION }} -m "Release v${{ steps.create_tag.outputs.TARGET_VERSION }}"
          git push https://github.com/cnc-csku/task-nexus-proto-go.git HEAD:main --tags
