name: "Generate go protos"
on:
  push:
    branches:
      - feature/*
env:
  GO_VERSION: 1.23
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: cnc-csku/task-nexus-proto-go
          ref: main
          path: task-nexus-proto-go

      - name: "Build protos"
        uses: bufbuild/buf-action@v1
        with:
          paths: task-nexus-proto-go
