name: "Generate go protos"
on:
  push:
    branches:
      - main
env:
  GO_VERSION: 1.23
jobs:
  generate:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Checkout proto-go repo
        uses: actions/checkout@v4
        with:
          repository: cnc-csku/task-nexus-proto-go
          ref: main
          path: task-nexus-proto-go
          token: ${{ secrets.GH_PAT }}

      - name: Set buf cli
        uses: bufbuild/buf-setup-action@v1

      - name: Build protos
        run: |
          cd task-nexus-proto-go
          buf generate

      - name: Create version tag
        id: create_tag
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          MAJOR=${{ vars.MAIN_MAJOR_VERSION }}
          MINOR=$((${{ vars.MAIN_MINOR_VERSION }} + 1))
          PATCH=0

          gh variable set MAIN_MINOR_VERSION --body $MINOR
          
          echo "TARGET_VERSION=v$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT

      - name: Commit generated code
        run: |
          cd task-nexus-proto-go
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Update generated proto to v${{ steps.create_tag.outputs.TARGET_VERSION }}"
          git tag ${{ steps.create_tag.outputs.TARGET_VERSION }}
          git push https://github.com/cnc-csku/task-nexus-proto-go.git HEAD:main --tags

      - name: Tag version
        id: tag_version
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.create_tag.outputs.TARGET_VERSION }}
          git push --tags
