name: "Generate go protos"
on:
  push:
    branches:
      - feature/*

env:
  GO_VERSION: 1.23
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install protoc
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
